language: node_js
node_js:
  - "0.10.25"
before_install: npm install -g grunt-cli
install: npm install
before_script:
  - grunt build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: grunt karma:travis